---

- name: fail on unsupported init systems
  assert:
    that:
      - ansible_service_mgr == "systemd"
    fail_msg: "this role work only with systemd distributives"

- name: is define telegram_token
  assert:
    that:
      - webhook2telegram_token is match('[\d{8,12}]+:\w{30,36}')
    fail_msg: "telegram_token is required"

- name: Populate service facts
  service_facts:
  when: not webhook2telegram_force_install
  
- name: fail on service is installed
  assert:
    that:
      - "'webhook2telegram.service' not in services"
    fail_msg: "webhook2telegram is already installed"
  when: not webhook2telegram_force_install

- name: is define bind_ip
  assert:
    that:
      - webhook2telegram_ip is match('^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$')
    fail_msg: " IP XXX.XXX.XXX.XXX is required"

- name: check comditions on https webhook
  block:
    - name: is define right port
      assert:
        that:
          - ( webhook2telegram_port == 8443 ) or ( webhook2telegram_port == 443 ) or ( webhook2telegram_port == 80 ) or ( webhook2telegram_port == 88 )
        fail_msg: "you mast set only 443, 80, 88, or 8443 port"
  when: webhook2telegram_https
